exports.ActionTypes = {
  SEND_BROADCAST_MESSAGES: 'SEND_BROADCAST_MESSAGES',
  GET_TEMPLATES: 'GET_TEMPLATES',
  SEND_INVITATION_TEMPLATE: 'SEND_INVITATION_TEMPLATE',
  SET_WEBHOOK: 'SET_WEBHOOK',
  VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS',
  CHECK_TWILLO_VERSION: ' CHECK_TWILLO_VERSION'
}
