exports.ActionTypes = {
  VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS',
  SET_WEBHOOK: 'SET_WEBHOOK',
  SEND_TEXT_MESSAGE: 'SEND_TEXT_MESSAGE',
  SEND_MEDIA_MESSAGE: 'SEND_MEDIA_MESSAGE',
  FETCH_AVAILABLE_NUMBERS: 'FETCH_AVAILABLE_NUMBERS',
  CREATE_ORDER: 'CREATE_ORDER'
}
